//! HTML-4 named character entities, for XMLTV documents that use them.
//!
//! XML defines exactly five named entities; guides routinely emit the HTML set
//! anyway. Without this table one `&eacute;` makes `quick-xml` fail the whole
//! text node, which is how a non-English provider's guide arrives full of blank
//! titles with nothing in the logs. Declaring them in a DOCTYPE internal subset
//! would do the same job; a table is simpler and leaves the document alone.
//!
//! The five XML-predefined names are here too. `quick-xml`'s `unescape_with`
//! *replaces* its built-in set with the supplied resolver rather than falling
//! back to it, so omitting them would break `&amp;` — the one entity every
//! guide uses.

/// Sorted by name so lookups can binary search.
static HTML_ENTITIES: &[(&str, &str)] = &[
    ("AElig", "\u{00c6}"),
    ("Aacute", "\u{00c1}"),
    ("Acirc", "\u{00c2}"),
    ("Agrave", "\u{00c0}"),
    ("Alpha", "\u{0391}"),
    ("Aring", "\u{00c5}"),
    ("Atilde", "\u{00c3}"),
    ("Auml", "\u{00c4}"),
    ("Beta", "\u{0392}"),
    ("Ccedil", "\u{00c7}"),
    ("Chi", "\u{03a7}"),
    ("Dagger", "\u{2021}"),
    ("Delta", "\u{0394}"),
    ("ETH", "\u{00d0}"),
    ("Eacute", "\u{00c9}"),
    ("Ecirc", "\u{00ca}"),
    ("Egrave", "\u{00c8}"),
    ("Epsilon", "\u{0395}"),
    ("Eta", "\u{0397}"),
    ("Euml", "\u{00cb}"),
    ("Gamma", "\u{0393}"),
    ("Iacute", "\u{00cd}"),
    ("Icirc", "\u{00ce}"),
    ("Igrave", "\u{00cc}"),
    ("Iota", "\u{0399}"),
    ("Iuml", "\u{00cf}"),
    ("Kappa", "\u{039a}"),
    ("Lambda", "\u{039b}"),
    ("Mu", "\u{039c}"),
    ("Ntilde", "\u{00d1}"),
    ("Nu", "\u{039d}"),
    ("OElig", "\u{0152}"),
    ("Oacute", "\u{00d3}"),
    ("Ocirc", "\u{00d4}"),
    ("Ograve", "\u{00d2}"),
    ("Omega", "\u{03a9}"),
    ("Omicron", "\u{039f}"),
    ("Oslash", "\u{00d8}"),
    ("Otilde", "\u{00d5}"),
    ("Ouml", "\u{00d6}"),
    ("Phi", "\u{03a6}"),
    ("Pi", "\u{03a0}"),
    ("Prime", "\u{2033}"),
    ("Psi", "\u{03a8}"),
    ("Rho", "\u{03a1}"),
    ("Scaron", "\u{0160}"),
    ("Sigma", "\u{03a3}"),
    ("THORN", "\u{00de}"),
    ("Tau", "\u{03a4}"),
    ("Theta", "\u{0398}"),
    ("Uacute", "\u{00da}"),
    ("Ucirc", "\u{00db}"),
    ("Ugrave", "\u{00d9}"),
    ("Upsilon", "\u{03a5}"),
    ("Uuml", "\u{00dc}"),
    ("Xi", "\u{039e}"),
    ("Yacute", "\u{00dd}"),
    ("Yuml", "\u{0178}"),
    ("Zeta", "\u{0396}"),
    ("aacute", "\u{00e1}"),
    ("acirc", "\u{00e2}"),
    ("acute", "\u{00b4}"),
    ("aelig", "\u{00e6}"),
    ("agrave", "\u{00e0}"),
    ("alefsym", "\u{2135}"),
    ("alpha", "\u{03b1}"),
    ("amp", "&"),
    ("and", "\u{2227}"),
    ("ang", "\u{2220}"),
    ("apos", "'"),
    ("aring", "\u{00e5}"),
    ("asymp", "\u{2248}"),
    ("atilde", "\u{00e3}"),
    ("auml", "\u{00e4}"),
    ("bdquo", "\u{201e}"),
    ("beta", "\u{03b2}"),
    ("brvbar", "\u{00a6}"),
    ("bull", "\u{2022}"),
    ("cap", "\u{2229}"),
    ("ccedil", "\u{00e7}"),
    ("cedil", "\u{00b8}"),
    ("cent", "\u{00a2}"),
    ("chi", "\u{03c7}"),
    ("circ", "\u{02c6}"),
    ("clubs", "\u{2663}"),
    ("cong", "\u{2245}"),
    ("copy", "\u{00a9}"),
    ("crarr", "\u{21b5}"),
    ("cup", "\u{222a}"),
    ("curren", "\u{00a4}"),
    ("dArr", "\u{21d3}"),
    ("dagger", "\u{2020}"),
    ("darr", "\u{2193}"),
    ("deg", "\u{00b0}"),
    ("delta", "\u{03b4}"),
    ("diams", "\u{2666}"),
    ("divide", "\u{00f7}"),
    ("eacute", "\u{00e9}"),
    ("ecirc", "\u{00ea}"),
    ("egrave", "\u{00e8}"),
    ("empty", "\u{2205}"),
    ("emsp", "\u{2003}"),
    ("ensp", "\u{2002}"),
    ("epsilon", "\u{03b5}"),
    ("equiv", "\u{2261}"),
    ("eta", "\u{03b7}"),
    ("eth", "\u{00f0}"),
    ("euml", "\u{00eb}"),
    ("euro", "\u{20ac}"),
    ("exist", "\u{2203}"),
    ("fnof", "\u{0192}"),
    ("forall", "\u{2200}"),
    ("frac12", "\u{00bd}"),
    ("frac14", "\u{00bc}"),
    ("frac34", "\u{00be}"),
    ("frasl", "\u{2044}"),
    ("gamma", "\u{03b3}"),
    ("ge", "\u{2265}"),
    ("gt", ">"),
    ("hArr", "\u{21d4}"),
    ("harr", "\u{2194}"),
    ("hearts", "\u{2665}"),
    ("hellip", "\u{2026}"),
    ("iacute", "\u{00ed}"),
    ("icirc", "\u{00ee}"),
    ("iexcl", "\u{00a1}"),
    ("igrave", "\u{00ec}"),
    ("image", "\u{2111}"),
    ("infin", "\u{221e}"),
    ("int", "\u{222b}"),
    ("iota", "\u{03b9}"),
    ("iquest", "\u{00bf}"),
    ("isin", "\u{2208}"),
    ("iuml", "\u{00ef}"),
    ("kappa", "\u{03ba}"),
    ("lArr", "\u{21d0}"),
    ("lambda", "\u{03bb}"),
    ("lang", "\u{2329}"),
    ("laquo", "\u{00ab}"),
    ("larr", "\u{2190}"),
    ("lceil", "\u{2308}"),
    ("ldquo", "\u{201c}"),
    ("le", "\u{2264}"),
    ("lfloor", "\u{230a}"),
    ("lowast", "\u{2217}"),
    ("loz", "\u{25ca}"),
    ("lrm", "\u{200e}"),
    ("lsaquo", "\u{2039}"),
    ("lsquo", "\u{2018}"),
    ("lt", "<"),
    ("macr", "\u{00af}"),
    ("mdash", "\u{2014}"),
    ("micro", "\u{00b5}"),
    ("middot", "\u{00b7}"),
    ("minus", "\u{2212}"),
    ("mu", "\u{03bc}"),
    ("nabla", "\u{2207}"),
    ("nbsp", "\u{00a0}"),
    ("ndash", "\u{2013}"),
    ("ne", "\u{2260}"),
    ("ni", "\u{220b}"),
    ("not", "\u{00ac}"),
    ("notin", "\u{2209}"),
    ("nsub", "\u{2284}"),
    ("ntilde", "\u{00f1}"),
    ("nu", "\u{03bd}"),
    ("oacute", "\u{00f3}"),
    ("ocirc", "\u{00f4}"),
    ("oelig", "\u{0153}"),
    ("ograve", "\u{00f2}"),
    ("oline", "\u{203e}"),
    ("omega", "\u{03c9}"),
    ("omicron", "\u{03bf}"),
    ("oplus", "\u{2295}"),
    ("or", "\u{2228}"),
    ("ordf", "\u{00aa}"),
    ("ordm", "\u{00ba}"),
    ("oslash", "\u{00f8}"),
    ("otilde", "\u{00f5}"),
    ("otimes", "\u{2297}"),
    ("ouml", "\u{00f6}"),
    ("para", "\u{00b6}"),
    ("part", "\u{2202}"),
    ("permil", "\u{2030}"),
    ("perp", "\u{22a5}"),
    ("phi", "\u{03c6}"),
    ("pi", "\u{03c0}"),
    ("piv", "\u{03d6}"),
    ("plusmn", "\u{00b1}"),
    ("pound", "\u{00a3}"),
    ("prime", "\u{2032}"),
    ("prod", "\u{220f}"),
    ("prop", "\u{221d}"),
    ("psi", "\u{03c8}"),
    ("quot", "\""),
    ("rArr", "\u{21d2}"),
    ("radic", "\u{221a}"),
    ("rang", "\u{232a}"),
    ("raquo", "\u{00bb}"),
    ("rarr", "\u{2192}"),
    ("rceil", "\u{2309}"),
    ("rdquo", "\u{201d}"),
    ("real", "\u{211c}"),
    ("reg", "\u{00ae}"),
    ("rfloor", "\u{230b}"),
    ("rho", "\u{03c1}"),
    ("rlm", "\u{200f}"),
    ("rsaquo", "\u{203a}"),
    ("rsquo", "\u{2019}"),
    ("sbquo", "\u{201a}"),
    ("scaron", "\u{0161}"),
    ("sdot", "\u{22c5}"),
    ("sect", "\u{00a7}"),
    ("shy", "\u{00ad}"),
    ("sigma", "\u{03c3}"),
    ("sigmaf", "\u{03c2}"),
    ("sim", "\u{223c}"),
    ("spades", "\u{2660}"),
    ("sub", "\u{2282}"),
    ("sube", "\u{2286}"),
    ("sum", "\u{2211}"),
    ("sup", "\u{2283}"),
    ("sup1", "\u{00b9}"),
    ("sup2", "\u{00b2}"),
    ("sup3", "\u{00b3}"),
    ("supe", "\u{2287}"),
    ("szlig", "\u{00df}"),
    ("tau", "\u{03c4}"),
    ("there4", "\u{2234}"),
    ("theta", "\u{03b8}"),
    ("thetasym", "\u{03d1}"),
    ("thinsp", "\u{2009}"),
    ("thorn", "\u{00fe}"),
    ("tilde", "\u{02dc}"),
    ("times", "\u{00d7}"),
    ("trade", "\u{2122}"),
    ("uArr", "\u{21d1}"),
    ("uacute", "\u{00fa}"),
    ("uarr", "\u{2191}"),
    ("ucirc", "\u{00fb}"),
    ("ugrave", "\u{00f9}"),
    ("uml", "\u{00a8}"),
    ("upsih", "\u{03d2}"),
    ("upsilon", "\u{03c5}"),
    ("uuml", "\u{00fc}"),
    ("weierp", "\u{2118}"),
    ("xi", "\u{03be}"),
    ("yacute", "\u{00fd}"),
    ("yen", "\u{00a5}"),
    ("yuml", "\u{00ff}"),
    ("zeta", "\u{03b6}"),
    ("zwj", "\u{200d}"),
    ("zwnj", "\u{200c}"),
];

pub fn lookup(name: &str) -> Option<&'static str> {
    HTML_ENTITIES
        .binary_search_by(|(candidate, _)| (*candidate).cmp(name))
        .ok()
        .map(|i| HTML_ENTITIES[i].1)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn resolves_the_names_guides_actually_emit() {
        let cases = [
            ("eacute", "\u{e9}"),
            ("nbsp", "\u{a0}"),
            ("copy", "\u{a9}"),
            ("mdash", "\u{2014}"),
            ("hellip", "\u{2026}"),
            ("uuml", "\u{fc}"),
            ("deg", "\u{b0}"),
            ("trade", "\u{2122}"),
        ];
        for (name, want) in cases {
            assert_eq!(lookup(name), Some(want), "{name}");
        }
    }

    #[test]
    fn resolves_the_xml_predefined_names_too() {
        // quick-xml's resolver hook replaces its built-in table, so these have
        // to be answered here or `&amp;` stops working.
        let cases = [
            ("amp", "&"),
            ("lt", "<"),
            ("gt", ">"),
            ("quot", "\""),
            ("apos", "'"),
        ];
        for (name, want) in cases {
            assert_eq!(lookup(name), Some(want), "{name}");
        }
    }

    #[test]
    fn rejects_unknown_names() {
        for name in ["notanentity", "", "EACUTE", "amp;"] {
            assert_eq!(lookup(name), None, "{name}");
        }
    }

    #[test]
    fn the_table_is_sorted_and_complete() {
        assert!(HTML_ENTITIES.windows(2).all(|w| w[0].0 < w[1].0));
        // The 252 HTML 4 names plus `apos`.
        assert_eq!(HTML_ENTITIES.len(), 253);
    }
}
