//! The SPA's route manifest, checked against the router that must serve it.
//!
//! `web/route-manifest.json` is generated by calling the frontend's resource
//! layer with a stubbed `fetch` and recording the URLs it actually produces —
//! so it is what the client calls, not a second hand-maintained list. This side
//! asserts the server answers every one of them.
//!
//! It exists because the frontend's own endpoint test asserts a literal in
//! `resources.js` against itself and would pass green against a wrong path. A
//! renamed route should fail a test, not 404 at runtime.
//!
//! The manifest is a *lower bound*. HDHomeRun, `/output/*` and the Xtream API
//! are not in it because the SPA never calls them — those are Plex's routes and
//! are covered by the golden-file corpus instead.

use axum::Router;
use axum::body::Body;
use axum::extract::ConnectInfo;
use axum::http::{Request, StatusCode};
use serde::Deserialize;
use std::net::SocketAddr;
use std::path::PathBuf;
use std::sync::Arc;
use tower::ServiceExt;

use dollet_core::config::TrustedProxies;

use crate::AppState;

#[derive(Debug, Deserialize)]
struct Route {
    name: String,
    method: String,
    path: String,
    auth: String,
}

#[derive(Debug, Deserialize)]
struct Manifest {
    routes: Vec<Route>,
}

fn manifest() -> Manifest {
    let path = PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../web/route-manifest.json");
    let raw = std::fs::read_to_string(&path)
        .unwrap_or_else(|e| panic!("reading {}: {e}", path.display()));
    serde_json::from_str(&raw).expect("route-manifest.json is not the shape this test expects")
}

/// A fallback nothing else returns, so "this path is not registered" is
/// unambiguous. Using the real SPA fallback would make the answer depend on
/// whether `web/dist` happens to have been built.
const UNROUTED: StatusCode = StatusCode::IM_A_TEAPOT;

async fn router() -> (Router, tempfile::TempDir) {
    let dir = tempfile::tempdir().expect("temp dir");
    let state = AppState {
        db: crate::test_support::migrated_db(dir.path()).await,
        config: Arc::new(crate::test_support::config(
            dir.path(),
            TrustedProxies::PrivateAndLoopback,
        )),
    };

    let router = Router::new()
        .nest("/api", crate::api::router())
        .merge(crate::api::public_router())
        .fallback(|| async { UNROUTED })
        .with_state(state);

    (router, dir)
}

async fn status_of(router: &Router, route: &Route) -> StatusCode {
    let mut request = Request::builder()
        .method(route.method.as_str())
        .uri(&route.path)
        .body(Body::empty())
        .expect("build request");

    request
        .extensions_mut()
        .insert(ConnectInfo(SocketAddr::from(([127, 0, 0, 1], 40000))));

    router
        .clone()
        .oneshot(request)
        .await
        .expect("router responded")
        .status()
}

#[tokio::test]
async fn every_route_the_spa_calls_is_served() {
    let (router, _dir) = router().await;
    let mut unrouted = Vec::new();

    for route in manifest().routes {
        if status_of(&router, &route).await == UNROUTED {
            unrouted.push(format!("{} {} ({})", route.method, route.path, route.name));
        }
    }

    assert!(
        unrouted.is_empty(),
        "the SPA calls {} route(s) the server does not serve:\n  {}",
        unrouted.len(),
        unrouted.join("\n  ")
    );
}

#[tokio::test]
async fn every_authenticated_route_actually_requires_a_token() {
    let (router, _dir) = router().await;
    let mut ungated = Vec::new();

    for route in manifest().routes.iter().filter(|r| r.auth == "bearer") {
        // No Authorization header. Anything other than 401 means the token the
        // client sends is not what is keeping this endpoint shut.
        let status = status_of(&router, route).await;
        if status != StatusCode::UNAUTHORIZED {
            ungated.push(format!(
                "{} {} ({}) answered {status}",
                route.method, route.path, route.name
            ));
        }
    }

    assert!(
        ungated.is_empty(),
        "{} route(s) the client authenticates are not gated:\n  {}",
        ungated.len(),
        ungated.join("\n  ")
    );
}

#[test]
fn the_manifest_covers_the_surface_it_claims_to() {
    let manifest = manifest();

    assert!(
        manifest.routes.len() > 40,
        "only {} routes — the generator probably recorded nothing",
        manifest.routes.len()
    );

    for route in &manifest.routes {
        assert!(
            matches!(route.auth.as_str(), "bearer" | "subprotocol" | "none"),
            "{}: unknown auth kind {:?}",
            route.name,
            route.auth
        );
        assert!(route.path.starts_with('/'), "{}: relative path", route.name);
    }
}
